; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:frdm_kl25z]
platform = freescalekinetis
board = frdm_kl25z
upload_protocol = jlink
debug_tool = jlink   
build_type = debug  ; needs to be debug for ozone to work properly
debug_init_break = tbreak main 
board_build.ldscript = ld_script/mkl25z128_vectab_ram.ld
debug_svd_path = svd/MKL25Z4.svd ; svd file contains peripheral register definitions for debugging

; monitor setup (comunication with target via UART)
monitor_speed = 115200
monitor_port = COM1

; build flags for compiler and linker
build_flags = 
    -std=gnu11
    -DSECURITY_EN=0
    -DRST_PIN_EN=1
    -DNMI_EN=0
    -DASSERT_BKPT=1
    -g3
    -Wall
    -ffreestanding
    -ffunction-sections
    -fdata-sections
    ; include paths for SDK
    -I sdk/_board
    -I sdk/_board/bm
    -I sdk/_board/os
    -I sdk/_cmsis
    -I sdk/_os
    -I sdk/_os/include
    -I sdk/_os/portable/gcc/arm_cm0
    -I sdk/_soc_def
    -I sdk/_syst
    -I sdk/_syst/bm
    -I sdk/_syst/os
    -I sdk/_util
    -I sdk
    -Wno-unused-but-set-variable
    
build_src_filter =
    +<*> 
    +<../sdk/**> ; include all SDK files

    ; turn off default startup files
    -<../sdk/**/*startup*.*>
    -<../sdk/**/*vectors*.c>
    -<../sdk/**/heap*.c> ; remove all heap implementations

    ; include custom startup file (connected with selected ldscript)
    +<../sdk/_cmsis/startup_MKL25Z4_vectab_ram.S>
    +<../sdk/_os/portable/memmang/heap_2.c> ; use heap_2 implementation


