/*
 * Name: system_MKL25Z4.c
 * Author: Martin Stankus
 *
 */

#include "MKL25Z4.h"

#include "soc_def.h"
#include "bme.h"

uint32_t SystemCoreClock;

void SystemInit(void)
{
	SIM->CLKDIV1 = 0ul;

	OSC0->CR = OSC_CR_ERCLKEN_MASK | OSC_CR_EREFSTEN_MASK;

	//FEI to FBE

	MCG->C2 = MCG_C2_LOCRE0_MASK | MCG_C2_RANGE0_VAL | MCG_C2_EREFS0_MASK;
	MCG->C1 = MCG_C1_CLKS_VAL_EXT;

	while (!BME_UBFX_B(&MCG->S, MCG_S_OSCINIT0_SHIFT, 1u));
	while (BME_UBFX_B(&MCG->S, MCG_S_IREFST_SHIFT, 1u));
	while (BME_UBFX_B(&MCG->S, MCG_S_CLKST_SHIFT, 2u) != (MCG_S_CLKST_VAL_EXT >> MCG_S_CLKST_SHIFT));

	//FBE to PBE

	MCG->C5 = MCG_C5_PLLSTEN0_MASK | MCG_C5_PRDIV0_VAL;
	MCG->C6 = MCG_C6_PLLS_MASK | MCG_C6_CME0_MASK | MCG_C6_VDIV0_VAL;

	while (!BME_UBFX_B(&MCG->S, MCG_S_PLLST_SHIFT, 1u));
	while (!BME_UBFX_B(&MCG->S, MCG_S_LOCK0_SHIFT, 1u));

	MCG->C8 = MCG_C8_LOLRE_MASK;

	//PBE to PEE

	SIM->CLKDIV1 = SIM_CLKDIV1_OUTDIV1_VAL | SIM_CLKDIV1_OUTDIV4_VAL;

	MCG->C1 = MCG_C1_CLKS_VAL_FLLPLL | MCG_C1_IRCLKEN_MASK | MCG_C1_IREFSTEN_MASK;

	while (BME_UBFX_B(&MCG->S, MCG_S_CLKST_SHIFT, 2u) != (MCG_S_CLKST_VAL_PLL >> MCG_S_CLKST_SHIFT));

	SIM->SCGC4 = 0xFFFFFFFFul;
	SIM->SCGC5 = 0xFFFFFFFFul;
	SIM->SCGC6 = 0xFFFFFFFFul;
	SIM->SCGC7 = 0xFFFFFFFFul;

	SIM->SOPT1 = SIM_SOPT1_OSC32KSEL_VAL;
	SIM->SOPT2 = SIM_SOPT2_UART0SRC_VAL | SIM_SOPT2_TPMSRC_VAL |
				SIM_SOPT2_USBSRC_MASK | SIM_SOPT2_PLLFLLSEL_MASK;

#if (SIM_SOPT1_OSC32KSEL_VAL == SIM_SOPT1_OSC32KSEL_VAL_RTC_CLKIN)
	PORT_RTC_CLKIN->PCR[IOIND_RTC_CLKIN] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO);
#endif

	PMC->REGSC = PMC_REGSC_BGBE_MASK;
}

void SystemCoreClockUpdate(void)
{
	SystemCoreClock = CORE_FREQ;
}
